### ISSUE TITLE
No release

### ISSUE THREAD

**Issue by JoshuaBehrens** [soebbing/redirect-to-backend#2]
Please add a release tag

**Comment by soebbing** [comment]
Your wish is my command! The first tag and release have been made!

**Comment by JoshuaBehrens** [comment]
Thanks. Now it is easier to handle different versions in case we need to change something in this tremendously important plugin.

**Comment by soebbing** [comment]
At least SOMEONE recognizes the overwhelming significance this plugin has! 🥇
